Add warning for invalid parameters
Currently, when a parameter is formatted wrong sphinx dies with a
cryptic error message:

    AttributeError: 'str' object has no attribute 'items'

This happens because the parameter is not recognized as dict.

This patch adds a check that ensures parameters are formatted correctly
by verifying that they're dicts.

Change-Id: I0140336cdcd9fd1d356d1fa50fd8dd15790ef8bd