Raise warning if top-level value is not a dict
Given the following 'parameters.yaml' file:

  resources_query_granular:
    type: string
    in: query
    required: false
    description: |
      Some description here...
  min_version: 1.22

Clearly 'min_version' is indented at the wrong level. However, the error
message is pretty much useless:

  Exception occurred:
    File "./os_api_ref/__init__.py", line 261, in _check_yaml_sorting
      if value['in'] not in sections:
    TypeError: string indices must be integers, not str

It's obvious we should be saying _what_ is causing this issue. Start
doing this by way of an exception.

Change-Id: If68f82de1e3bf37b1ab89f12adf78e0d8d123674